---

"ow_delay": 30 #delay of oak wood in seconds

"sw_delay": 30 #delay of spruce wood in seconds

"bw_delay": 30 #delay of birch wood in seconds

"dow_delay": 30 #delay of dark oak wood in seconds

"aw_delay": 30 #delay of acacia wood in seconds

"jw_delay": 30 #delay of jungle wood in seconds

"levelname": "world" #In what world should the WoodGen Work

"oak_wood": true #Enable or disable oak wood gen

"spruce_wood": true #Enable or disable spruce wood gen

"birch_wood": true #Enable or disable birch wood gen

"dark_oak_wood": true #Enable or disable dark oak wood gen

"jungle_wood": true #Enable or disable jungle wood gen

"acacia_wood": true #Enable or disable acacia wood gen

...

